/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import org.example.core.HttpHandler
import org.example.core.routes

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }

    val app: HttpHandler = routes()
}

fun main() {
    println(App().greeting)
}
